layout_spectrum: 0.8996627
typography_spectrum: 0.05649241
color:
  lightness: 0.5042158
  brandStrength: 0.7598984
  saturation: 0.7655987
  rhythmicContrast: 0.623946
  brandColors:
    - '#FFFFFF'
    - '#414141'
    - '#FFD100'
    - '#4EC931'
    - '#E15280'
name: 'One of a Kind - Arts & Handicrafts'
