layout_spectrum: 0.8954469
name: 'One of a Kind - Arts & Handicrafts'
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.7598984
  lightness: 0.5042158
  saturation: 0.7655987
  rhythmicContrast: 0.623946
  brandColors:
    - '#FFFFFF'
    - '#414141'
    - '#FFD100'
    - '#4EC931'
    - '#E15280'
typography_spectrum: 0.4831366
